export const defaultCategories = [
  { name: 'Income', color: '#34D399', icon: 'trending-up' },
  { name: 'Housing', color: '#60A5FA', icon: 'home' },
  { name: 'Utilities', color: '#38BDF8', icon: 'bolt' },
  { name: 'Groceries', color: '#22C55E', icon: 'shopping-cart' },
  { name: 'Dining', color: '#FB7185', icon: 'utensils' },
  { name: 'Transport', color: '#2DD4BF', icon: 'car' },
  { name: 'Fuel', color: '#F97316', icon: 'fuel' },
  { name: 'Health', color: '#F472B6', icon: 'heart' },
  { name: 'Insurance', color: '#A78BFA', icon: 'shield-check' },
  { name: 'Debt', color: '#F87171', icon: 'credit-card' },
  { name: 'Shopping', color: '#FACC15', icon: 'shopping-bag' },
  { name: 'Entertainment', color: '#C084FC', icon: 'film' },
  { name: 'Education', color: '#14B8A6', icon: 'book' },
  { name: 'Travel', color: '#818CF8', icon: 'plane' },
  { name: 'Subscriptions', color: '#F59E0B', icon: 'repeat' },
  { name: 'Savings', color: '#7DD3FC', icon: 'piggy-bank' },
  { name: 'Gifts', color: '#F0ABFC', icon: 'gift' },
  { name: 'Personal Care', color: '#FDA4AF', icon: 'sparkles' },
  { name: 'Taxes', color: '#94A3B8', icon: 'receipt' },
  { name: 'Other', color: '#CBD5E1', icon: 'more-horizontal' },
];
